SELECT SUM(Altura) as SOMA_TOTAL FROM Aluno
SELECT SUM(Altura) as SOMA_ALTURA_REPROVADOS FROM Aluno WHERE Aprovado ='false';
SELECT COUNT(*) as TOTAL_REGISTROS FROM Aluno;
SELECT MAX(Altura) as MAIOR_ALTURA FROM Aluno
SELECT MIN(Altura) as MENOR_ALTURA FROM Aluno
SELECT COUNT (*) as APROVADOS FROM Aluno WHERE Aprovado='true'